CREATE TABLE [dbo].[Log]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), 
    [ReportId] UNIQUEIDENTIFIER NOT NULL, 
    [EventTimeUtc] DATETIME NOT NULL DEFAULT GETUTCDATE(), 
    [Action] NVARCHAR(MAX) NOT NULL, 
    [UpdatedBy] NVARCHAR(MAX) NOT NULL, 
    [ReportingData] NVARCHAR(MAX) NOT NULL, 
    CONSTRAINT [FK_Log_Report] FOREIGN KEY ([ReportId]) REFERENCES [Report]([Id])
)
