// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.PSRService.Web.Specflow.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ReportEdit - MPD-1135")]
    public partial class ReportEdit_MPD_1135Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ReportEdit.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ReportEdit - MPD-1135", "As a PSR user \r\nI want to be able to edit a report that has already been started " +
                    "\r\nSo that my organisation can submit information.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
testRunner.Given("Edit access is granted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
testRunner.And("a report has been created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
testRunner.And("the report has not been submitted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user can edit a report")]
        public virtual void UserCanEditAReport()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user can edit a report", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 12
 testRunner.Given("User navigates to the Edit report page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
 testRunner.Then("the edit report page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user can edit a report question")]
        public virtual void UserCanEditAReportQuestion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user can edit a report question", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 16
 testRunner.Given("User navigates to the Edit report page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
 testRunner.When("User clicks on \'Number of employees who work in England\' question link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
 testRunner.Then("the Your employees page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user can update YourEmployees question")]
        [NUnit.Framework.TestCaseAttribute("100", "150", "50", null)]
        [NUnit.Framework.TestCaseAttribute("1000", "750", "0", null)]
        [NUnit.Framework.TestCaseAttribute("850", "1000", "150", null)]
        [NUnit.Framework.TestCaseAttribute("850000", "1000000", "150", null)]
        public virtual void UserCanUpdateYourEmployeesQuestion(string atStart, string atEnd, string newThisPeriod, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user can update YourEmployees question", exampleTags);
#line 20
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 21
 testRunner.Given("User navigates to the Your employees question page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
 testRunner.And(string.Format("the your employees question values {0}, {1} and {2} have been edited", atStart, atEnd, newThisPeriod), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.When("User clicks on the save question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.Then(string.Format("The Your Employees question values {0}, {1} and {2} have been saved", atStart, atEnd, newThisPeriod), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user can update YourApprentices question")]
        [NUnit.Framework.TestCaseAttribute("100", "150", "50", null)]
        [NUnit.Framework.TestCaseAttribute("1000", "750", "0", null)]
        [NUnit.Framework.TestCaseAttribute("850", "1000", "150", null)]
        [NUnit.Framework.TestCaseAttribute("850000", "1000000", "150", null)]
        public virtual void UserCanUpdateYourApprenticesQuestion(string atStart, string atEnd, string newThisPeriod, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user can update YourApprentices question", exampleTags);
#line 33
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 34
 testRunner.Given("User navigates to the Your apprentices question page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 35
 testRunner.And(string.Format("the your apprentices question values {0}, {1} and {2} have been edited", atStart, atEnd, newThisPeriod), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.When("User clicks on the save question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
 testRunner.Then(string.Format("The Your Apprentices question values {0}, {1} and {2} have been saved", atStart, atEnd, newThisPeriod), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user can update FullTimeEquivalents question")]
        [NUnit.Framework.TestCaseAttribute("100", null)]
        [NUnit.Framework.TestCaseAttribute("1000", null)]
        [NUnit.Framework.TestCaseAttribute("850", null)]
        [NUnit.Framework.TestCaseAttribute("850000", null)]
        [NUnit.Framework.TestCaseAttribute("1000000", null)]
        public virtual void UserCanUpdateFullTimeEquivalentsQuestion(string answer, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user can update FullTimeEquivalents question", exampleTags);
#line 45
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 46
 testRunner.Given("User navigates to the Full time equivalent question page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 47
 testRunner.And(string.Format("the full time equivalents question value {0} has been edited", answer), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.When("User clicks on the save question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then(string.Format("The full time equivalents question value {0} has been saved", answer), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user can update Outline Actions question")]
        [NUnit.Framework.TestCaseAttribute("\"one\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"two\"", null)]
        [NUnit.Framework.TestCaseAttribute(@"""Maecenas enim lorem, pharetra sed iaculis eleifend, blandit ultrices urna. Nullam at cursus magna, et auctor lectus. Maecenas consectetur, nibh in dignissim dapibus, tortor magna fringilla urna, eget tempor tortor nibh vitae felis. Fusce auctor vitae nunc nec maximus. Praesent augue lacus, venenatis quis nisi eget, suscipit faucibus eros. Nullam maximus nibh non dictum tempus. Duis ac diam non ipsum ullamcorper fringilla eu ut felis. Sed massa justo, commodo et lacus at, fringilla dignissim tellus. Ut porttitor sem et lectus mattis commodo. Suspendisse iaculis dignissim mauris, in porta libero. Sed bibendum sapien nulla, sed sodales diam sagittis at. Curabitur id ipsum aliquet, cursus diam et, lacinia tortor. Nulla leo est, dapibus eget lacus ac, fringilla faucibus orci. Pellentesque nunc lectus, vehicula non arcu quis, ultrices viverra mi. Fusce ultricies sodales nisl, vitae hendrerit nunc suscipit ut. """, null)]
        public virtual void UserCanUpdateOutlineActionsQuestion(string answer_Text, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user can update Outline Actions question", exampleTags);
#line 58
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 59
 testRunner.Given("User navigates to the Outline Actions question page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 60
 testRunner.And(string.Format("User answers Outline Actions question with {0}", answer_Text), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.When("User clicks on the save question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
 testRunner.Then(string.Format("The outline actions question value {0} has been saved", answer_Text), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user can update Challenges question")]
        [NUnit.Framework.TestCaseAttribute("\"one\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"two\"", null)]
        [NUnit.Framework.TestCaseAttribute(@"Donec at iaculis mi. Duis in tempor libero. Aenean tortor augue, venenatis et leo in, laoreet bibendum sem. In scelerisque nisi et tincidunt maximus. Proin sagittis consequat velit, fermentum iaculis elit placerat et. Proin quis luctus tortor. Nullam nec tellus laoreet, tincidunt neque et, eleifend enim. Aliquam rutrum erat nunc, non congue sapien laoreet in. Aliquam eleifend mauris nunc. Sed at massa vulputate, laoreet ipsum eu, auctor neque. Maecenas elementum sed risus id posuere. Curabitur sit amet sem sed libero gravida efficitur vitae in erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum feugiat pulvinar ex, vitae aliquet eros ullamcorper ac. Phasellus vel sapien vitae odio vestibulum rutrum sed id ligula. Phasellus in felis id magna convallis semper quis non lectus.", null)]
        public virtual void UserCanUpdateChallengesQuestion(string answer_Text, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user can update Challenges question", exampleTags);
#line 69
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 70
 testRunner.Given("User navigates to the Challenges question page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 71
 testRunner.And(string.Format("User answers Challenges question with {0}", answer_Text), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.When("User clicks on the save question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
 testRunner.Then(string.Format("The Challenges question value {0} has been saved", answer_Text), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user can update Target Plans question")]
        [NUnit.Framework.TestCaseAttribute("\"one\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"two\"", null)]
        [NUnit.Framework.TestCaseAttribute(@"Curabitur ullamcorper augue nec tellus malesuada, sit amet facilisis nisl dignissim. Nulla eu gravida nulla, ut venenatis sapien. Phasellus aliquet orci ac lorem placerat, nec lobortis turpis consectetur. Mauris eu congue magna, eget cursus dolor. Fusce ex urna, accumsan vel dolor vel, dapibus consectetur tortor. Pellentesque maximus lobortis tortor, non pharetra neque commodo at. Phasellus odio dolor, consequat eget est non, semper iaculis metus. Curabitur elementum nulla risus, eget placerat erat facilisis in. Praesent feugiat ante sit amet rutrum eleifend. Phasellus eget maximus massa.", null)]
        public virtual void UserCanUpdateTargetPlansQuestion(string answer_Text, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user can update Target Plans question", exampleTags);
#line 80
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 81
 testRunner.Given("User navigates to the Target Plans question page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 82
 testRunner.And(string.Format("User answers Target Plans question with {0}", answer_Text), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.When("User clicks on the save question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 84
 testRunner.Then(string.Format("The Target Plans question value {0} has been saved", answer_Text), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user can update Anything Else question")]
        [NUnit.Framework.TestCaseAttribute("\"one\"", null)]
        [NUnit.Framework.TestCaseAttribute("\"two\"", null)]
        [NUnit.Framework.TestCaseAttribute(@"Ut vehicula rhoncus imperdiet. Suspendisse sit amet nunc ut ligula hendrerit consequat. Nullam sodales gravida tincidunt. Curabitur vitae elementum mi. Nunc in condimentum erat. Vivamus non consequat metus. Phasellus at tellus malesuada, convallis mi eget, consequat nulla. Mauris pretium mattis urna, et venenatis quam pellentesque condimentum. Donec pellentesque lectus a tellus dictum mollis. Quisque et sem felis. Duis sed elit at metus aliquet finibus ac id tellus. Aliquam pretium eleifend eleifend. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce semper aliquet condimentum. Aliquam at aliquet mi. Donec tincidunt, erat a aliquet rutrum, ipsum sapien egestas turpis, eu aliquet tortor urna sit amet justo.", null)]
        public virtual void UserCanUpdateAnythingElseQuestion(string answer_Text, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user can update Anything Else question", exampleTags);
#line 91
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 92
 testRunner.Given("User navigates to the Anything Else question page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 93
 testRunner.And(string.Format("User answers Anything Else question with {0}", answer_Text), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.When("User clicks on the save question", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 95
 testRunner.Then(string.Format("The Anything Else question value {0} has been saved", answer_Text), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
